tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-container": "#9800d0",
        "on-surface-variant": "#adaaaa",
        "on-primary-container": "#00555a",
        "surface-bright": "#2c2c2c",
        "on-background": "#ffffff",
        "on-tertiary-fixed": "#000c54",
        "inverse-on-surface": "#565554",
        "on-surface": "#ffffff",
        "surface-container-highest": "#262626",
        "tertiary-container": "#3956fb",
        "on-secondary-container": "#fff5fc",
        "on-error-container": "#ffa8a3",
        "error-dim": "#d7383b",
        "outline-variant": "#494847",
        "tertiary-fixed": "#9eabff",
        "on-tertiary": "#001269",
        "primary-dim": "#00e2ee",
        "secondary-fixed": "#f0c1ff",
        "surface": "#0e0e0e",
        "inverse-surface": "#fcf8f8",
        "primary": "#99f7ff",
        "primary-fixed-dim": "#00e2ee",
        "error": "#ff716c",
        "primary-fixed": "#00f1fe",
        "surface-variant": "#262626",
        "primary-container": "#00f1fe",
        "on-primary-fixed-variant": "#006065",
        "inverse-primary": "#006a70",
        "surface-tint": "#99f7ff",
        "surface-container-high": "#201f1f",
        "secondary-dim": "#b90afc",
        "on-secondary-fixed-variant": "#8300b4",
        "surface-container-low": "#131313",
        "surface-dim": "#0e0e0e",
        "on-secondary-fixed": "#58007a",
        "on-primary": "#005f64",
        "tertiary-fixed-dim": "#8d9cff",
        "on-error": "#490006",
        "secondary-fixed-dim": "#eaaeff",
        "outline": "#777575",
        "surface-container": "#1a1919",
        "on-primary-fixed": "#004145",
        "surface-container-lowest": "#000000",
        "background": "#0e0e0e",
        "error-container": "#9f0519",
        "on-tertiary-fixed-variant": "#0023ab",
        "tertiary-dim": "#4963ff",
        "secondary": "#d575ff",
        "tertiary": "#8596ff",
        "on-secondary": "#390050",
        "on-tertiary-container": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
}
